### ISSUE TITLE
Cannot install fleetctl, GYP failure

### ISSUE THREAD

**Issue by ccombs-sqsp** [kolide/homebrew-tap#4]
On Mac OSX 10.15.6
After running the following lines:
`brew tap kolide/tap`
`brew install fleet`

The fleet installation failed with the following error:

```
==> Installing kolide/tap/fleet
==> yarn
Last 15 lines from /Users/ccombs/Library/Logs/Homebrew/fleet/01.yarn:

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/tmp/fleet-20200914-5748-hl7cyw/fleet-2.0.0-rc2/gopath/src/github.com/kolide/fleet/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.10.1/bin/node" "/private/tmp/fleet-20200914-5748-hl7cyw/fleet-2.0.0-rc2/gopath/src/github.com/kolide/fleet/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /private/tmp/fleet-20200914-5748-hl7cyw/fleet-2.0.0-rc2/gopath/src/github.com/kolide/fleet/node_modules/node-sass
gyp ERR! node -v v14.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
```

**Comment by ccombs-sqsp** [comment]
After reinstalling xcode tools as described [here](https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d), tried to install and got the following error:
```
==> yarn
Last 15 lines from /Users/ccombs/Library/Logs/Homebrew/fleet/01.yarn:
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/tmp/fleet-20200915-10410-gm7r62/fleet-2.0.0-rc2/gopath/src/github.com/kolide/fleet/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.10.1/bin/node" "/private/tmp/fleet-20200915-10410-gm7r62/fleet-2.0.0-rc2/gopath/src/github.com/kolide/fleet/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /private/tmp/fleet-20200915-10410-gm7r62/fleet-2.0.0-rc2/gopath/src/github.com/kolide/fleet/node_modules/node-sass
gyp ERR! node -v v14.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
```
